### ISSUE TITLE
Github Page not working

### ISSUE THREAD

**Issue by TheDogHusky** [Shimeri/Domesticated-Catgirl#3]
Have a 404 error when trying to access the Gh Page

**Comment by Xprogrammer777** [comment]
Bro changed username so the link is now : https://nullcano.github.io/Domesticated-Catgirl/

**Comment by Xprogrammer777** [comment]
Also omg wtf is this project

**Comment by TheDogHusky** [comment]
Some weebus stuff xD
Also thanks
